api/urls.py
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import SimpleRouter
from api import views

router = SimpleRouter()
router.register('posts', views.PostViewSet)

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/api-token-auth/', obtain_auth_token),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

posts/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница с постами, отфильтрованными по группам
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Добавление поста
    path('create/', views.create_post, name='post_create'),
    # редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),

    # добавление комментария
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube_projects/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.generic import TemplateView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Posts API",
        default_version='v1',
        description="Документация для приложения posts проекта Yatube",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@yatube.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

posts/models.py
from django.db import models
from django.urls import path
from django.contrib.auth import get_user_model

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.TextField(
        'Название группы',
        help_text='Напишите, как будет называться ваша группа'
    )
    slug = models.SlugField(
        'Никнейм вашей группы',
        help_text='Придумайте сокращенное название вашей группы'
    )
    description = models.TextField(
        'Описание группы',
        help_text='Добавьте описание для вашей группы'
    )

    def __str__(self):
        return self.title


class Tag(CreatedModel):
    name = models.TextField(
        'Наименование хэштега'
    )

    def __str__(self):
        return self.name


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Напишите текст, который хотите опубликовать'
    )

    group = models.ForeignKey(
        Group,
        related_name='posts',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )

    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    tag = models.ManyToManyField(
        Tag,
        through='TagPost'
    )

    def __str__(self):
        # выводим текст поста
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        verbose_name='Пост',
        on_delete=models.CASCADE,
    )

    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Автор',
    )

    text = models.TextField(
        'Комментарий',
        help_text='Напишите комментарий',
    )

    def __str__(self):
        return self.text[:15]


class TagPost(CreatedModel):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.tag} {self.post}'

posts/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

posts/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.shortcuts import redirect
from posts.models import Post, Group, Comment
from django.contrib.auth import get_user_model
from .forms import PostForm, CommentForm


# Главная страница
def index(request):
    template = "posts/index.html"
    post_list = Post.objects.all().order_by('-created')
    paginator = Paginator(post_list, 10)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)
    context = {
        'page_number': page_number,
        'page_obj': page_obj,
    }
    return render(request, template, context)


# Страница с постами, отфильтрованными по группам
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)

    posts = Post.objects.filter(group=group).order_by('-created')
    # Показывать по 10 записей на странице.
    paginator = Paginator(posts, 10)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(get_user_model(), username=username)
    author_posts = Post.objects.filter(author=author).order_by('-created')
    paginator = Paginator(author_posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'username': username,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post).order_by('-created')
    author = post.author
    author_count_posts = Post.objects.filter(author=author).count()
    form = CommentForm(
        request.POST or None,
    )
    context = {
        'post': post,
        'author_count_posts': author_count_posts,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def create_post(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=Post(author=request.user)
    )

    if form.is_valid():
        form.save()
        return redirect(f'/profile/{request.user.username}/')

    template_name = 'posts/create_post.html'
    context = {
        'form': form
    }
    return render(request, template_name, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('posts:index')

@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Создание поста{% endblock %}
{% block content %}
    {% load user_filters %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if is_edit %}
                            Редактировать пост
                        {% else %}
                            Новый пост
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" action="
                            {% if is_edit %}
                                {% url 'posts:post_edit' post.id %}
                            {% else %}
                                {% url 'posts:post_create' %}
                            {% endif %}">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group row my-3"
                                        {% if field.field.required %}
                                     aria-required="true"
                                        {% else %}
                                     aria-required="false"
                                        {% endif %}
                                >
                                    <label for="{{ field.id_for_label }}">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="required text-danger">*</span>
                                        {% endif %}
                                    </label>
                                    <div>
                                        {{ field|addclass:'form-control' }}
                                        {% if field.help_text %}
                                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                                {{ field.help_text|safe }}
                                            </small>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                        Сохранить
                                    {% else %}
                                        Добавить
                                    {% endif %}
                                </button>
                            </div>
                        </form>
                        <div class="d-flex justify-content-end">
                            <form method="post" action="
                                {% url 'posts:post_delete' post.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                        Удалить
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}

    <div class="container py-5">

        <h1>{{ group.title }}</h1>
        <h3>{{ group.description }}</h3>


        {% for post in page_obj %}
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "1024x784" upscale=True as im %}
                <img class="my-2" src="{{ im.url }}" width="300px" height="300px" alt="image">
            {% endthumbnail %}
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}

        {% include 'posts/includes/paginator.html' %}
    </div>

{% endblock %}

templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    

    <div class="container">
        <div class="container">
                {% for post in page_obj %}
                    <strong>
                        Автор: {{ post.author.get_full_name }}
                        <br> Дата публикации: {{ post.created|date:"d M Y" }}
                        {% if post.group.slug is not None %}
                            <br> Группа:
                            <a href="{% url 'posts:group_posts' post.group.slug %}">{{ post.group.title }}</a>
                        {% else %}
                            <br> Группы нет.
                        {% endif %}
                        <br><a href="{% url 'posts:post_detail' post.id %}">смотреть запись </a>
                        {% if user == post.author %}
                            <br><a href="{% url 'posts:post_edit' post.id %}">редактировать запись </a>
                        {% endif %}
                    </strong>
                    <p>{{ post.text|linebreaksbr }}</p>
                    {% thumbnail post.image "1024x784" upscale=True as im %}
                        <img class="my-2" src="{{ im.url }}" width="300px" height="300px" alt="image">
                    {% endthumbnail %}
                    <hr>
                {% endfor %}
        </div>
        {% include 'posts/includes/paginator.html' %}
    </div>

{% endblock %}

templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row">
            <article>
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                {% thumbnail post.image "1024x784" upscale=True as im %}
                    <img class="my-2" src="{{ im.url }}" width="300px" height="300px" alt="image">
                {% endthumbnail %}
                <p>{{ post.text }}</p>
                <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            </article>
        </div>
        {% include 'posts/includes/comments.html' %}
    </div>
{% endblock %}

templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ username }}{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>Все посты пользователя {{ username }}</h1>
        <h3>Всего постов: {{ page_obj|length }} </h3>
        <article>
            {% for post in page_obj %}
                <ul>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>{{ post.text }}</p>
                {% thumbnail post.image "1024x784" upscale=True as im %}
                    <img class="my-2" src="{{ im.url }}" width="300px" height="300px"  alt="image">
                {% endthumbnail %}
                <br><a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
                {% if user.username == username %}
                    <br><a href="{% url 'posts:post_edit' post.id %}">редактировать запись </a>
                {% else %}
                    <br><a href="{% url 'posts:post_detail' post.id %}">смотреть запись </a>
                {% endif %}

                {% if post.group is not None %}
                    <br><a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
                {% else %}
                    <br> Группы нет.
                {% endif %}
                {% if not forloop.last %}
                    <hr>{% endif %}
            {% endfor %}
        </article>

        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}