api/urls.py
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import SimpleRouter
from api import views

router = SimpleRouter()
router.register('posts', views.PostViewSet)

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/api-token-auth/', obtain_auth_token),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

posts/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница с постами, отфильтрованными по группам
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Добавление поста
    path('create/', views.create_post, name='post_create'),
    # редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),

    # добавление комментария
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.contrib.auth.views import *
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),

    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube_projects/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.generic import TemplateView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Posts API",
        default_version='v1',
        description="Документация для приложения posts проекта Yatube",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@yatube.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</nav>

templates/includes/header.html
{% with request.resolver_match.view_name as view_name %}
    <header>
        <nav class="navbar navbar-light" style="background-color: lightskyblue">
            <div class="container">
                <a class="navbar-brand" href="{% url 'posts:index' %}">
                    <span style="color:red">Ya</span>tube
                </a>
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
                           href="{% url 'about:author' %}">Об авторе</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
                           href="{% url 'about:tech' %}">Технологии</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}"
                               href="{% url 'users:password_change' %}">Изменить пароль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                        </li>
                        <li>
                            <a class="nav-link {% if view_name  == 'posts:profile' %}active{% endif %}"
                               href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
                        <li>
                            {% else %}
                        <li class="nav-item">
                            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
                               href="{% url 'users:login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
                               href="{% url 'users:signup' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
{% endwith %}