api/urls.py
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import SimpleRouter
from api import views

router = SimpleRouter()
router.register('posts', views.PostViewSet)

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/api-token-auth/', obtain_auth_token),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

posts/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница с постами, отфильтрованными по группам
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Добавление поста
    path('create/', views.create_post, name='post_create'),
    # редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),

    # добавление комментария
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.contrib.auth.views import *
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),

    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube_projects/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.generic import TemplateView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Posts API",
        default_version='v1',
        description="Документация для приложения posts проекта Yatube",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@yatube.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

        fields = ('first_name', 'last_name', 'username', 'email')

users/views.py
# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
    {% load user_filters %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Войти на сайт
                </div>
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post"
                            {% if action_url %}
                          action="{% url 'users:login' %}"
                            {% endif %}
                    >
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row my-3"
                                    {% if field.field.required %}
                                 aria-required="true"
                                    {% else %}
                                 aria-required="false"
                                    {% endif %}
                            >
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                <div>
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                            {{ field.help_text|safe }}
                                        </small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Войти
                            </button>
                            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
                            не существует. Нужно что-то делать, иначе все упадет -->
                            <a type="submit" href="{% url 'users:password_reset' %}" class="btn btn-link">
                                Забыли пароль?
                            </a>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock %} 

templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Пароль изменён
                    </div>
                    <div class="card-body">
                        <p>Пароль изменён успешно</p>
                    </div> <!-- card body -->
                </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
    </div>
{% endblock %}

templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    {% load user_filters %}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" action="{% url 'users:password_change' %}">
                        {% csrf_token %}
                        {# Выводим поля в цикле, по отдельности #}
                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {# К полю ввода добавляем атрибут class #}
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                    <small
                                            id="{{ field.id_for_label }}-help"
                                            class="form-text text-muted"
                                    >
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Изменить пароль
                            </button>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock %}

templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошел успешно{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
    {% load user_filters %}
    {% if validlink %}
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">
                            Введите новый пароль
                        </div>
                        <div class="card-body">
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endif %}

                            <form method="post">
                                {% csrf_token %}

                                {# Выводим поля в цикле, по отдельности #}
                                {% for field in form %}
                                    <div class="form-group row my-3">
                                        <label for="{{ field.id_for_label }}">
                                            {{ field.label }}
                                            {% if field.field.required %}
                                                <span class="required text-danger">*</span>
                                            {% endif %}
                                        </label>
                                        {# К полю ввода добавляем атрибут class #}
                                        {{ field|addclass:'form-control' }}
                                        {% if field.help_text %}
                                            <small
                                                    id="{{ field.id_for_label }}-help"
                                                    class="form-text text-muted"
                                            >
                                                {{ field.help_text|safe }}
                                            </small>
                                        {% endif %}
                                    </div>
                                {% endfor %}

                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Назначить новый пароль
                                    </button>
                                </div>
                            </form>
                        </div> <!-- card body -->
                    </div> <!-- card -->
                </div> <!-- col -->
            </div> <!-- row -->
        </div> <!-- container -->
    {% else %}
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Ошибка
                    </div>
                    <div class="card-body">
                        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
                    </div> <!-- card body -->
                </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
    {% endif %}
{% endblock %}

templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Отправлено письмо
                    </div>
                    <div class="card-body">
                        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
                    </div>
                    <div class="card-body">
                        {% load user_filters %} {# Загружаем фильтры #}
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endif %}

                        <form method="post" action="{% url 'users:password_reset' %}">
                            {% csrf_token %}

                            {# Выводим поля в цикле, по отдельности #}
                            {% for field in form %}
                                <div class="form-group row my-3">
                                    <label for="{{ field.id_for_label }}">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="required text-danger">*</span>
                                        {% endif %}
                                    </label>
                                    {# К полю ввода добавляем атрибут class #}
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small
                                                id="{{ field.id_for_label }}-help"
                                                class="form-text text-muted"
                                        >
                                            {{ field.help_text|safe }}
                                        </small>
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Сбросить пароль
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Зарегистрироваться</div>
                <div class="card-body">
                    {% load user_filters %} {# Загружаем фильтры #}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post"
                            {% if action_url %}
                          action="{% url 'posts:post_create' %}"
                            {% endif %}
                    >
                        {% csrf_token %}

                        {# Выводим поля в цикле, по отдельности #}
                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {# К полю ввода добавляем атрибут class #}
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                    <small
                                            id="{{ field.id_for_label }}-help"
                                            class="form-text text-muted"
                                    >
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock %} 